---
title: "Plotly and flexdashboard"
output: 
  html_document:
    toc: true
    toc_float: true
---
This parge is about making plotly
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

Let's look at the NYC airbnb data


```{r}
data("nyc_airbnb")

nyc_airbnb <- 
  nyc_airbnb %>% 
  mutate(stars = review_scores_location/2) %>% 
  select(neighbourhood_group,neighbourhood,stars,price,room_type,lat,long) %>% 
  filter(
    neighbourhood_group == "Manhattan",
    room_type == "Entire home/apt",
    price %in% 100:500
  ) %>% 
  drop_na(stars)
```

## Make a scatterplot

```{r}
nyc_airbnb %>% 
  mutate(
    text_label = str_c("Price:$",price,"\nRating:",stars)
  ) %>% 
  plot_ly(
    x = ~lat, y = ~long, type = "scatter", mode = "markers",
    color =  ~price,text = ~text_label, alpha = 0.5
  )
```

## Plotly boxplot

```{r}
nyc_airbnb %>% 
  mutate(
    neighbourhood = fct_reorder(neighbourhood,price)
  ) %>% 
  plot_ly(
    y = ~price, color = ~neighbourhood,type = "box",
    colors = "viridis"
  )
```

## plotly barplot

```{r}
nyc_airbnb %>% 
  count(neighbourhood) %>% 
  mutate(
    neighbourhood = fct_reorder(neighbourhood,n)
  ) %>% 
  plot_ly(
    x = ~neighbourhood, y = ~n, color = ~neighbourhood,type = "bar",
    colors = "viridis"
  )
```

## ggplotly

```{r}
gg_lat_long <- 
  nyc_airbnb %>% 
  ggplot(aes(x = lat, y =long,color=price))+ 
  geom_point()

ggplotly(gg_lat_long)
```

